### PR TITLE
List structure

### PR DESCRIPTION
**Pull request by arthurborgesdev**
This was the beginning of the Todo List app development

Things developed so far:

- Set up linters on the project
- Set up Webpack
- Add HTML template to webpack setup
- Add CSS to webpack setup with fontawesome for icons
- Add JavaScript with the list and function to add each object in its own format to the page
- Style the application to be like the proposed design
- Fix the linters
- Write documentation in README.md

### CODE REVIEW

**Review by mricanho — CHANGES_REQUESTED** [review]
Hi @arthurborgesdev, 

Good job so far! 🔥🔥 Your JS code is completed and your webpack configuration, your README file looks like a pro.

There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️

- [ ] Double check your PopulateTodos function, right now doesn't work
- [ ] You need to achieve the targeted styling

Your style:

imagen

Target style:

imagen


_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by arthurborgesdev** [comment]
Note for the next reviewer:

This is the output running on a friend's (@fernandorpm - Fernando Marques) computer:

After he just runs:

- `npm install`
- `npm run start` 

WhatsApp Image 2021-07-13 at 22 03 06

**Comment by Spayco** [comment]
Hello 👋,

This is an additional review as a result of the second opinion request.

During the program, when a certain task is optional, it will be made clear that it is, and it will be in the **`Additional requirements`** section, check [this project](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/8_popup.md#additional-requirements) for example

That being said, the review is valid, and the page should look like the design in the video (but not exactly since there are some features not included yet)

Good luck with the project!

**Comment by arthurborgesdev** [comment]
@Spayco, I think you do not saw my comment... the problem is not the lack of features, the problem is that the reviewer could not see my final project.

**Comment by Spayco** [comment]
Hi again @arthurborgesde 👋 

This is an additional review as a result of the second opinion request.

Sorry about that, I got mixed up with another PR, I deleted the comment to remove confusion to the next Code Reviewer,

But you are right, the webpage does load fine, but I noticed that the styles weren't showing up for a few moments before it loaded, the code reviewer may have had a slow internet/computer which didn't let them notice the style.

As this was the only reason that your project was not approved it will be approved as soon as possible.
Please ask for another review in your Dashboard and the next Code Reviewer will mark it as approve right away :) sorry for the inconvenience!

Best of luck with future projects, and keep rocking 🚀!

**Review by voscarmv — APPROVED** [review]
Hi @arthurborgesdev , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
